### ISSUE TITLE
Manque l'implémentation des comptes : Client/Employé/Administrateur

### ISSUE THREAD

**Issue by Zakaria13rfs** [Belleau6744/inf1583-gestion-pompe#1]
Manque l'implémentation des comptes : Client/Employé/Administrateur. Possible que chacun a son interface après authentification (nom d'utilisateur et mot de passe) ?

**Comment by Belleau6744** [comment]
1. Oui on peut certainement séparer les interfaces en fonctions des rôles. 
2. J'ai l'impression que le compte 'client' n'est pas vraiment un type de compte. Dans une station service, un client n'aurait pas à se connecter. Mais on pourrait peut-être montrer ce que le client peut voir

**Comment by Zakaria13rfs** [comment]
Puisqu'on peut visualiser le fonctionnement de la pompe et l'interface de choix de paiement (carte/compte client/espèces), je trouve qu'il est nécessaire d'avoir un compte client. En revanche, pour d'autres fonctionnalités, telles que la configuration de la pompe ou factures impayés cela n'est pas nécessaire pour le client.

**Comment by Zakaria13rfs** [comment]
Le Compte Client doit seulement avoir accès à la pompe.
![image](https://github.com/user-attachments/assets/6821cf75-4e92-489c-9058-90dbbba5b4f3)

Le Compte Employé doit avoir accès à tout sauf aux paramètres. Il est également nécessaire de créer une interface permettant de saisir les matricules des voitures qui ne paient pas la facture : "Des clients parfois s’enfuient sans payer et le surveillant note la transaction avec toute information disponible comme l’immatriculation de la voiture".
![image](https://github.com/user-attachments/assets/b71d37a5-db85-4f54-92fc-1aa8f2f4e399)


Le Compte Administrateur doit pouvoir accéder à l'ensemble du système.
![image](https://github.com/user-attachments/assets/4e4aeee7-3f07-44d8-8434-852c6a0c0213)

**Comment by Zakaria13rfs** [comment]
Les comptes Admin et Client sont maintenant conforment. Par contre il reste une authentification au compte Employé avec nom utilisateur/mot de passe  : il doit avoir accès à tout sauf aux paramètres 
![image](https://github.com/user-attachments/assets/9bd8681b-c71f-485f-a64f-d6888e8e52b3)
